CREATE TABLE CATEGORY(
ID    INT8  NOT NULL,
NAME  VARCHAR(255) NOT NULL,
DESCRIPTION VARCHAR(255) NOT NULL,
ACTIVE  BOOLEAN DEFAULT TRUE,
PARENT_ID INT8   REFERENCES CATEGORY (ID),
primary key (ID)
);

CREATE TABLE BOOK(
ID    INT8  NOT NULL,
NAME  VARCHAR(255) NOT NULL,
DESCRIPTION VARCHAR(255) NOT NULL,
YEAR  INT8 NOT NULL,
AUTHOR VARCHAR(255) NOT NULL,
ACTIVE  BOOLEAN DEFAULT TRUE,
CATEGORY_ID INT8   REFERENCES CATEGORY (ID),
primary key (ID)
);


INSERT INTO category(id,name,description,active)
VALUES(1,'Root','Root Category',true);

	